dist: trusty
services:
  - postgresql
matrix:
  include:
    - language: python
      python: 
        - "3.6"
      install:
        - pip install -r requirements.txt
      before_script:
        - psql -c 'create database test_dbTreating warnings as errors because process.env.CI = true.;' -U postgres
      script:
        - python manage.py test
    - language: node_js
      node_js:
        - "10"
      cache:
        directories:
          client/node_modules
      before_install:
        - cd client
      install:
        - npm install
        - CI=false npm run build
      script:
        - nohup npm run start &
        - sleep 3
        - npm run test
